root = "."
tmp_dir = "tmp_audit"

[build]
  cmd = "go mod download && go build -buildvcs=false -o ./tmp_audit/audit ./cmd/audit"
  entrypoint = "./tmp_audit/audit"
  include_ext = ["go"]
  exclude_dir = ["tmp", "tmp_consumer", "tmp_outbox", "tmp_webhook", "tmp_notification", "tmp_audit", "vendor"]
  delay = 500
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
